// <auto-generated />
using System;
using LegalStrategyAdvisor.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LegalStrategyAdvisor.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LegalStrategyAdvisor.Api.Data.Entities.Case", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cases");
                });

            modelBuilder.Entity("LegalStrategyAdvisor.Api.Data.Entities.LegalStrategy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LegalStrategies");
                });

            modelBuilder.Entity("LegalStrategyAdvisor.Api.Data.Entities.Precedent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CaseType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Citation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Jurisdiction")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("RelevanceScore")
                        .HasPrecision(3, 2)
                        .HasColumnType("double precision");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CaseType");

                    b.HasIndex("Jurisdiction");

                    b.HasIndex("Year");

                    b.ToTable("Precedents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CaseType = "Civil Rights",
                            Citation = "Brown v. Board of Education, 347 U.S. 483 (1954)",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Jurisdiction = "United States Supreme Court",
                            RelevanceScore = 0.94999999999999996,
                            Summary = "Landmark decision declaring state laws establishing separate public schools for black and white students to be unconstitutional.",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Year = 1954
                        },
                        new
                        {
                            Id = 2,
                            CaseType = "Criminal",
                            Citation = "Miranda v. Arizona, 384 U.S. 436 (1966)",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Jurisdiction = "United States Supreme Court",
                            RelevanceScore = 0.90000000000000002,
                            Summary = "Established that suspects must be informed of their rights before interrogation, including the right to remain silent and right to an attorney.",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Year = 1966
                        },
                        new
                        {
                            Id = 3,
                            CaseType = "Constitutional",
                            Citation = "Roe v. Wade, 410 U.S. 113 (1973)",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Jurisdiction = "United States Supreme Court",
                            RelevanceScore = 0.84999999999999998,
                            Summary = "Established constitutional right to abortion under the Due Process Clause of the Fourteenth Amendment.",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Year = 1973
                        },
                        new
                        {
                            Id = 4,
                            CaseType = "Constitutional",
                            Citation = "Marbury v. Madison, 5 U.S. 137 (1803)",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Jurisdiction = "United States Supreme Court",
                            RelevanceScore = 0.92000000000000004,
                            Summary = "Established the principle of judicial review, allowing courts to declare laws unconstitutional.",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Year = 1803
                        },
                        new
                        {
                            Id = 5,
                            CaseType = "Corporate",
                            Citation = "Citizens United v. FEC, 558 U.S. 310 (2010)",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Jurisdiction = "United States Supreme Court",
                            RelevanceScore = 0.80000000000000004,
                            Summary = "Held that corporations and unions have the same political speech rights as individuals under the First Amendment.",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Year = 2010
                        });
                });

            modelBuilder.Entity("LegalStrategyAdvisor.Api.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
